// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/series/series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/series.dart' as _i10;
import 'package:ditonton/domain/entities/series_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_series_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_series_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/remove_series_watchlist.dart' as _i6;
import 'package:ditonton/domain/usecases/save_series_watchlist.dart' as _i5;
import 'package:ditonton/presentation/provider/series/series_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetSeriesDetail {
  _FakeGetSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSeriesRecommendations_1 extends _i1.SmartFake
    implements _i3.GetSeriesRecommendations {
  _FakeGetSeriesRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListSeriesStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchListSeriesStatus {
  _FakeGetWatchListSeriesStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveSeriesWatchlist_3 extends _i1.SmartFake
    implements _i5.SaveSeriesWatchlist {
  _FakeSaveSeriesWatchlist_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveSeriesWatchlist_4 extends _i1.SmartFake
    implements _i6.RemoveSeriesWatchlist {
  _FakeRemoveSeriesWatchlist_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeriesDetail_5 extends _i1.SmartFake implements _i7.SeriesDetail {
  _FakeSeriesDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesDetailNotifier extends _i1.Mock
    implements _i8.SeriesDetailNotifier {
  MockSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSeriesDetail get getSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getSeriesDetail),
        returnValue: _FakeGetSeriesDetail_0(
          this,
          Invocation.getter(#getSeriesDetail),
        ),
      ) as _i2.GetSeriesDetail);

  @override
  _i3.GetSeriesRecommendations get getSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getSeriesRecommendations),
        returnValue: _FakeGetSeriesRecommendations_1(
          this,
          Invocation.getter(#getSeriesRecommendations),
        ),
      ) as _i3.GetSeriesRecommendations);

  @override
  _i4.GetWatchListSeriesStatus get getWatchListSeriesStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchListSeriesStatus),
        returnValue: _FakeGetWatchListSeriesStatus_2(
          this,
          Invocation.getter(#getWatchListSeriesStatus),
        ),
      ) as _i4.GetWatchListSeriesStatus);

  @override
  _i5.SaveSeriesWatchlist get saveSeriesWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveSeriesWatchlist),
        returnValue: _FakeSaveSeriesWatchlist_3(
          this,
          Invocation.getter(#saveSeriesWatchlist),
        ),
      ) as _i5.SaveSeriesWatchlist);

  @override
  _i6.RemoveSeriesWatchlist get removeSeriesWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeSeriesWatchlist),
        returnValue: _FakeRemoveSeriesWatchlist_4(
          this,
          Invocation.getter(#removeSeriesWatchlist),
        ),
      ) as _i6.RemoveSeriesWatchlist);

  @override
  _i7.SeriesDetail get series => (super.noSuchMethod(
        Invocation.getter(#series),
        returnValue: _FakeSeriesDetail_5(
          this,
          Invocation.getter(#series),
        ),
      ) as _i7.SeriesDetail);

  @override
  _i9.RequestState get seriesState => (super.noSuchMethod(
        Invocation.getter(#seriesState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  List<_i10.Series> get seriesRecommendation => (super.noSuchMethod(
        Invocation.getter(#seriesRecommendation),
        returnValue: <_i10.Series>[],
      ) as List<_i10.Series>);

  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> fetchSeriesDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchSeriesDetail,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addWatchlist(_i7.SeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [series],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeFromWatchlist(_i7.SeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [series],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
